# Generated by Django 4.1.3 on 2022-12-04 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='posts/<django.db.models.fields.related.ForeignKey>')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_images', to='blog.post')),
            ],
        ),
    ]
