# Generated by Django 4.1.3 on 2022-12-04 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_articleimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='updated_time',
            field=models.DateField(auto_now=True),
        ),
    ]
